resources:
  - ../base

namespace: <team-name> # fix me

images:
  - name: mongodb
    newTag: latest # change to the MongoDB version you want to use

patches:
  - target: 
      kind: Secret
      name: mongodb-secret
    patch: |-
      - op: replace
        path: /stringDat
        value:
          MONGO_INITDB_ROOT_USERNAME: myuser
          MONGO_INITDB_ROOT_PASSWORD: mypassword
          # MONGO_INITDB_DATABASE: myapp
  
  # colloction 생성 시 아래 코드를 참고하여 사용하세요
  # host: mongodb-0.mongodb.<team-name>.svc.cluster.local:27017 

  # - target:
  #     kind: Job
  #     name: mongosh
  #   patch: |-
  #     apiVersion: batch/v1
  #     kind: Job
  #     metadata:
  #       name: mongosh
  #     spec:
  #       template:
  #         spec:
  #           containers:
  #           - name: mongosh
  #             command:
  #             - /bin/bash
  #             - -c
  #             - |
  #               mongosh "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-0.mongodb.<team-name>.svc.cluster.local:27017/admin" \
  #               --eval 'db = db.getSiblingDB("myapp"); db.createCollection("init_check"); print("✅ myapp DB and collection created.");'